// @neuron-ui/components - UI component library

// Utility
export { cn } from './lib/utils'

// shadcn primitives (Layer 1)
export { Button, buttonVariants } from './ui/button'
export type { ButtonProps } from './ui/button'
export { Badge, badgeVariants } from './ui/badge'
export type { BadgeProps } from './ui/badge'
export { Avatar, AvatarImage, AvatarFallback } from './ui/avatar'
export { Input } from './ui/input'
export { Label } from './ui/label'
export { Separator } from './ui/separator'
export { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent } from './ui/card'
export { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogFooter, DialogTitle, DialogDescription, DialogClose } from './ui/dialog'
export { AlertDialog, AlertDialogTrigger, AlertDialogContent, AlertDialogHeader, AlertDialogFooter, AlertDialogTitle, AlertDialogDescription, AlertDialogAction, AlertDialogCancel } from './ui/alert-dialog'
export { Sheet, SheetTrigger, SheetContent, SheetHeader, SheetFooter, SheetTitle, SheetDescription, SheetClose } from './ui/sheet'
export { ScrollArea, ScrollBar } from './ui/scroll-area'
export { Tabs, TabsList, TabsTrigger, TabsContent } from './ui/tabs'
export { Collapsible, CollapsibleTrigger, CollapsibleContent } from './ui/collapsible'
export { Select, SelectGroup, SelectValue, SelectTrigger, SelectContent, SelectLabel, SelectItem, SelectSeparator } from './ui/select'
export { Checkbox } from './ui/checkbox'
export { RadioGroup, RadioGroupItem } from './ui/radio-group'
export { Switch } from './ui/switch'
export { Textarea } from './ui/textarea'
export { Slider } from './ui/slider'

// Neuron components (Layer 2) — P0 Core
export { NButton } from './neuron/NButton'
export type { NButtonProps, NButtonVariant, NButtonSize } from './neuron/NButton'
export { NBadge } from './neuron/NBadge'
export type { NBadgeProps, NBadgeVariant, NBadgeSize, NBadgeColor } from './neuron/NBadge'
export { NAvatar } from './neuron/NAvatar'
export type { NAvatarProps, NAvatarSize, NAvatarShape, NAvatarStatus } from './neuron/NAvatar'
export { NInput } from './neuron/NInput'
export type { NInputProps, NInputSize } from './neuron/NInput'
export { NLabel } from './neuron/NLabel'
export type { NLabelProps } from './neuron/NLabel'
export { NText } from './neuron/NText'
export type { NTextProps, NTextSize, NTextWeight, NTextAs, NTextColor } from './neuron/NText'
export { NSeparator } from './neuron/NSeparator'
export type { NSeparatorProps, NSeparatorOrientation } from './neuron/NSeparator'
export { NSpinner } from './neuron/NSpinner'
export type { NSpinnerProps, NSpinnerSize } from './neuron/NSpinner'

// Neuron components (Layer 2) — P1 Container
export { NCard } from './neuron/NCard'
export type { NCardProps, NCardVariant } from './neuron/NCard'
export { NDialog } from './neuron/NDialog'
export type { NDialogProps } from './neuron/NDialog'
export { NAlertDialog } from './neuron/NAlertDialog'
export type { NAlertDialogProps } from './neuron/NAlertDialog'
export { NSheet } from './neuron/NSheet'
export type { NSheetProps, NSheetSide } from './neuron/NSheet'
export { NDrawer } from './neuron/NDrawer'
export type { NDrawerProps } from './neuron/NDrawer'
export { NAspectRatio } from './neuron/NAspectRatio'
export type { NAspectRatioProps } from './neuron/NAspectRatio'
export { NScrollArea } from './neuron/NScrollArea'
export type { NScrollAreaProps, NScrollAreaOrientation } from './neuron/NScrollArea'
export { NTabs, NTabsContent } from './neuron/NTabs'
export type { NTabsProps, NTabItem } from './neuron/NTabs'
export { NBreadcrumb } from './neuron/NBreadcrumb'
export type { NBreadcrumbProps, NBreadcrumbItem } from './neuron/NBreadcrumb'
export { NSidebar } from './neuron/NSidebar'
export type { NSidebarProps } from './neuron/NSidebar'
export { NCollapsible } from './neuron/NCollapsible'
export type { NCollapsibleProps } from './neuron/NCollapsible'

// Neuron components (Layer 2) — P2 Form
export { NInputGroup } from './neuron/NInputGroup'
export type { NInputGroupProps } from './neuron/NInputGroup'
export { NCombobox } from './neuron/NCombobox'
export type { NComboboxProps, NComboboxOption } from './neuron/NCombobox'
export { NSelect } from './neuron/NSelect'
export type { NSelectProps, NSelectOption } from './neuron/NSelect'
export { NCheckbox } from './neuron/NCheckbox'
export type { NCheckboxProps } from './neuron/NCheckbox'
export { NRadioGroup } from './neuron/NRadioGroup'
export type { NRadioGroupProps, NRadioGroupOption } from './neuron/NRadioGroup'
export { NSwitch } from './neuron/NSwitch'
export type { NSwitchProps } from './neuron/NSwitch'
export { NTextarea } from './neuron/NTextarea'
export type { NTextareaProps } from './neuron/NTextarea'
export { NDatePicker } from './neuron/NDatePicker'
export type { NDatePickerProps } from './neuron/NDatePicker'
export { NSlider } from './neuron/NSlider'
export type { NSliderProps } from './neuron/NSlider'
export { NInputOTP } from './neuron/NInputOTP'
export type { NInputOTPProps } from './neuron/NInputOTP'
export { NField } from './neuron/NField'
export type { NFieldProps } from './neuron/NField'

// shadcn primitives (Layer 1) — P3 Display
export { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from './ui/accordion'
export { Progress } from './ui/progress'
export { HoverCard, HoverCardTrigger, HoverCardContent } from './ui/hover-card'
export { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuLabel, DropdownMenuGroup, DropdownMenuSub, DropdownMenuSubTrigger, DropdownMenuSubContent } from './ui/dropdown-menu'
export { ContextMenu, ContextMenuTrigger, ContextMenuContent, ContextMenuItem, ContextMenuSeparator } from './ui/context-menu'
export { Skeleton } from './ui/skeleton'
export { Table, TableHeader, TableBody, TableFooter, TableRow, TableHead, TableCell, TableCaption } from './ui/table'

// Neuron components (Layer 2) — P3 Display
export { NDataTable } from './neuron/NDataTable'
export type { NDataTableProps, NDataTableColumn } from './neuron/NDataTable'
export { NCalendar } from './neuron/NCalendar'
export type { NCalendarProps } from './neuron/NCalendar'
export { NCarousel } from './neuron/NCarousel'
export type { NCarouselProps } from './neuron/NCarousel'
export { NDropdownMenu } from './neuron/NDropdownMenu'
export type { NDropdownMenuProps, NDropdownMenuItem } from './neuron/NDropdownMenu'
export { NContextMenu } from './neuron/NContextMenu'
export type { NContextMenuProps, NContextMenuItem } from './neuron/NContextMenu'
export { NEmpty } from './neuron/NEmpty'
export type { NEmptyProps } from './neuron/NEmpty'
export { NAccordion } from './neuron/NAccordion'
export type { NAccordionProps, NAccordionItem } from './neuron/NAccordion'
export { NAlert } from './neuron/NAlert'
export type { NAlertProps, NAlertVariant } from './neuron/NAlert'
export { NProgress } from './neuron/NProgress'
export type { NProgressProps } from './neuron/NProgress'
export { NSkeleton } from './neuron/NSkeleton'
export type { NSkeletonProps } from './neuron/NSkeleton'
export { NHoverCard } from './neuron/NHoverCard'
export type { NHoverCardProps } from './neuron/NHoverCard'
export { NPagination } from './neuron/NPagination'
export type { NPaginationProps } from './neuron/NPagination'
export { NChart } from './neuron/NChart'
export type { NChartProps, NChartType, NChartDataPoint } from './neuron/NChart'

// shadcn primitives (Layer 1) — P4 Auxiliary
export { Toggle, toggleVariants } from './ui/toggle'
export { ToggleGroup, ToggleGroupItem } from './ui/toggle-group'
export { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from './ui/tooltip'
export { Popover, PopoverTrigger, PopoverContent } from './ui/popover'
export { Menubar, MenubarMenu, MenubarTrigger, MenubarContent, MenubarItem, MenubarSeparator } from './ui/menubar'
export { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuTrigger, NavigationMenuContent, NavigationMenuLink, navigationMenuTriggerStyle } from './ui/navigation-menu'

// Neuron components (Layer 2) — P4 Auxiliary
export { NToast } from './neuron/NToast'
export type { NToastProps } from './neuron/NToast'
export { NToggle } from './neuron/NToggle'
export type { NToggleProps } from './neuron/NToggle'
export { NToggleGroup } from './neuron/NToggleGroup'
export type { NToggleGroupProps, NToggleGroupItem } from './neuron/NToggleGroup'
export { NResizable } from './neuron/NResizable'
export type { NResizableProps } from './neuron/NResizable'
export { NTooltip } from './neuron/NTooltip'
export type { NTooltipProps } from './neuron/NTooltip'
export { NPopover } from './neuron/NPopover'
export type { NPopoverProps } from './neuron/NPopover'
export { NCommand } from './neuron/NCommand'
export type { NCommandProps, NCommandItem } from './neuron/NCommand'
export { NMenubar } from './neuron/NMenubar'
export type { NMenubarProps, NMenubarMenu, NMenubarMenuItem } from './neuron/NMenubar'
export { NNavigationMenu } from './neuron/NNavigationMenu'
export type { NNavigationMenuProps, NNavigationMenuItemConfig } from './neuron/NNavigationMenu'
export { NKbd } from './neuron/NKbd'
export type { NKbdProps } from './neuron/NKbd'
